export const FETCH_USER='FETCH_USER';
// export const FETCH_FOOD_TYPE='FETCH_FOOD_TYPE';
// export const FETCH_RESTAURANT_TYPE='FETCH_RESTAURANT_TYPE';
// export const FETCH_RESTAURANT='FETCH_RESTAURANT';